# Generated by Django 4.2.2 on 2023-07-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='pass1',
        ),
    ]
