# Generated by Django 4.2.2 on 2023-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_authuser_pass1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
