# Generated by Django 4.2.3 on 2023-07-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_alter_authuser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='phone_no',
            new_name='phone_number',
        ),
    ]
